// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOF8uWrkXLAJao5JowmhR5WUiaQ9JEnaM',
    appId: '1:38038261577:web:6d7a54a1d3518b3008d498',
    messagingSenderId: '38038261577',
    projectId: 'looksmart-b7df5',
    authDomain: 'looksmart-b7df5.firebaseapp.com',
    storageBucket: 'looksmart-b7df5.firebasestorage.app',
    measurementId: 'G-PJR3W9CQ4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSpTHSUt2icj2NBIly9RUml3d2SaRNXQg',
    appId: '1:38038261577:android:e97ebb7aad39192f08d498',
    messagingSenderId: '38038261577',
    projectId: 'looksmart-b7df5',
    storageBucket: 'looksmart-b7df5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5QMN1muYB8OlYQm1OSjGslmP72h-Q-w',
    appId: '1:38038261577:ios:074dc11ffe3c485608d498',
    messagingSenderId: '38038261577',
    projectId: 'looksmart-b7df5',
    storageBucket: 'looksmart-b7df5.firebasestorage.app',
    iosBundleId: 'com.example.lookSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5QMN1muYB8OlYQm1OSjGslmP72h-Q-w',
    appId: '1:38038261577:ios:074dc11ffe3c485608d498',
    messagingSenderId: '38038261577',
    projectId: 'looksmart-b7df5',
    storageBucket: 'looksmart-b7df5.firebasestorage.app',
    iosBundleId: 'com.example.lookSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOF8uWrkXLAJao5JowmhR5WUiaQ9JEnaM',
    appId: '1:38038261577:web:75685f8fe0b6c8be08d498',
    messagingSenderId: '38038261577',
    projectId: 'looksmart-b7df5',
    authDomain: 'looksmart-b7df5.firebaseapp.com',
    storageBucket: 'looksmart-b7df5.firebasestorage.app',
    measurementId: 'G-QQ6PZV4VG2',
  );
}
